# Checks if files were committed with the right copyright headers
#

on:
  pull_request:

jobs:
  consistency-checks:
    name: "Code Consistency Checks"
    runs-on: ubuntu-latest

    steps:
      - name: "Fetch source code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0 # We need to do comparisons against the main branch.
      - name: Setup Copywrite
        uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          # Newer versions of `copywrite` are broken in the OpenTofu project, because
          # they handle the legacy project headers differently. We shouldn't upgrade
          # past 0.24.2.
          version: v0.24.2
      - name: "Copyright headers"
        run: |
          copywrite headers --plan
          if [[ $? != 0 ]]; then
            echo >&2 "ERROR: some files are missing required copyright headers. Take a look at the .copywrite.hcl file to see which headers are expected."
            exit 1
          fi
